# Generated by Django 5.2 on 2025-04-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transportcost', models.PositiveIntegerField()),
                ('utilitycost', models.PositiveIntegerField()),
                ('foodcost', models.PositiveIntegerField()),
                ('safetyrating', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='location_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('criminal_history', models.BooleanField(default=False)),
                ('employment_status', models.BooleanField(default=False)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='owner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Studio', 'Studio'), ('Villa', 'Villa'), ('Commercial', 'Commercial'), ('Flat', 'Flat')], max_length=50)),
                ('description', models.TextField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('total_rooms', models.IntegerField()),
                ('floor_level', models.CharField(max_length=50)),
                ('total_floors', models.IntegerField()),
                ('property_size', models.CharField(max_length=50)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Negotiable', 'Negotiable')], max_length=20)),
                ('balcony_terrace', models.BooleanField()),
                ('parking_space', models.BooleanField()),
                ('garden_yard', models.BooleanField()),
                ('swimming_pool', models.BooleanField()),
                ('lift_elevator', models.BooleanField()),
                ('pet_friendly', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('property_image', models.ImageField(upload_to='property_images/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinehousingapp.location')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinehousingapp.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('criminal_history', models.BooleanField(default=False)),
                ('employment_status', models.BooleanField(default=False)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='tenant_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinehousingapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinehousingapp.user'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinehousingapp.user')),
            ],
        ),
    ]
