# Generated by Django 5.2 on 2025-04-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='criminal_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='employment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='criminal_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='employment_status',
            field=models.BooleanField(default=False),
        ),
    ]
