# Generated by Django 5.1.4 on 2025-04-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('criminalhistory', models.BooleanField(default=False)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transportcost', models.PositiveIntegerField()),
                ('utilitycost', models.PositiveIntegerField()),
                ('foodcost', models.PositiveIntegerField()),
                ('safetyrating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('criminalhistory', models.BooleanField(default=False)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('criminalhistory', models.BooleanField(default=False)),
                ('employmentstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinehousingapp.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinehousingapp.owner'),
            preserve_default=False,
        ),
    ]
