# Generated by Django 5.2 on 2025-04-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0002_alter_owner_criminal_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='user',
            new_name='user_id',
        ),
    ]
