# Generated by Django 5.2 on 2025-04-13 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='onlinehousingapp.location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='onlinehousingapp.owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_size',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
