# Generated by Django 5.1.4 on 2025-04-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0002_booking_location_owner_tenant_property_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='limage',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
