# Generated by Django 5.2 on 2025-04-23 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0002_rename_garden_yard_property_co_living_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupancy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinehousingapp.tenant'),
        ),
    ]
