# Generated by Django 5.2 on 2025-04-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0003_rename_user_owner_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='user_id',
            new_name='user',
        ),
    ]
