# Generated by Django 5.2 on 2025-04-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0003_alter_occupancy_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='clothingcost',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='entertainmentcost',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='healthcarecost',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
