# Generated by Django 5.1.4 on 2025-04-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0003_location_limage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='limage',
        ),
    ]
