# Generated by Django 5.2 on 2025-04-11 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0004_rename_user_id_owner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Studio', 'Studio'), ('Villa', 'Villa'), ('Commercial', 'Commercial'), ('Flat', 'Flat')], max_length=50)),
                ('description', models.TextField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('total_rooms', models.IntegerField()),
                ('floor_level', models.CharField(max_length=50)),
                ('total_floors', models.IntegerField()),
                ('balcony_terrace', models.BooleanField()),
                ('property_size', models.CharField(max_length=50)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Negotiable', 'Negotiable')], max_length=20)),
                ('parking_space', models.BooleanField()),
                ('garden_yard', models.BooleanField()),
                ('swimming_pool', models.BooleanField()),
                ('lift_elevator', models.BooleanField()),
                ('pet_friendly', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('property_image', models.ImageField(upload_to='property_images/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinehousingapp.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinehousingapp.owner')),
            ],
        ),
    ]
