# Generated by Django 5.1.4 on 2025-04-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0004_remove_location_limage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='criminalhistory',
            new_name='criminal_history',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='employmentstatus',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='tenant',
            name='employment_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
