# Generated by Django 5.2 on 2025-04-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0004_location_clothingcost_location_entertainmentcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pethealthcost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
