# Generated by Django 5.1.4 on 2025-04-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehousingapp', '0005_rename_criminalhistory_tenant_criminal_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='employment_status',
            field=models.BooleanField(default=True),
        ),
    ]
